### ISSUE TITLE
Auto-setting $SERVER vars

### ISSUE THREAD

**Issue by karllhughes** [betterweekdays/glassdoor#15]
I noticed that users have to set `$_SERVER['REMOTE_ADDR']` and `$_SERVER['HTTP_USER_AGENT']` in order to use this client. What do you think about giving these some default values?

I usually do something like this:

```
$_SERVER['REMOTE_ADDR'] = getHostByName(getHostName());
$_SERVER['HTTP_USER_AGENT'] = 'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36';
```

**Comment by indytechcook** [comment]
Great idea.  Perhaps we add them to the config class.
