### ISSUE TITLE
Unit tests failing

### ISSUE THREAD

**Issue by karllhughes** [betterweekdays/glassdoor#5]
I noticed the unit tests are failing when I run this on my machine. 

I moved some stuff around and now they're all working for me. The main issue was some namespacing that wasn't set up properly. I've made the updates in [my own version of this repo](https://github.com/karllhughes/glassdoor) and would be happy to submit a PR if you're into updating this repo. 

Just let me know!

**Comment by indytechcook** [comment]
Yeah, I actually never ran the unit tests.  I set them up but didn't run them.  I meant to setup travis and such but didn't get to that either.

**Comment by karllhughes** [comment]
Cool. Are you interested in actively maintaining this repo? If so, I'll make a PR with unit tests fixed and add some issues to improve the project.

**Comment by indytechcook** [comment]
Yeah, we use it in production currently when importing in jobs from our feed, we pull data from glass door.

**Comment by karllhughes** [comment]
Sweet. I'll make a PR then, and I'll be careful about changing anything that could affect production code. Unit tests and travis will be my first priorities. Thanks.
