### ISSUE TITLE
Question: What do you think about PSR-2?

### ISSUE THREAD

**Issue by karllhughes** [betterweekdays/glassdoor#8]
Doesn't really improve performance, but with multiple devs working on this project, I tend to think it would be nice to adhere to some style standards. I like [PSR-2](http://www.php-fig.org/psr/psr-2/) and once I finish setting up Travis, we can have it automatically check against that styling standard.

Let me know if you think this is something worth doing. Thanks!

**Comment by indytechcook** [comment]
I'm actually not a fan of PSR-1 or 2.  I've used the [Drupal coding standards](https://www.drupal.org/coding-standards) as I feel they are much more concise and easier to read.

That being said, I do understand the value in the community standards and would begrudgingly accept using them :)

**Comment by karllhughes** [comment]
That's fair. As long as everybody is using the same standards on a project, I think it's fine. I'll look into adding a code sniffer to the testing process and see if we can get it to validate against the Drupal standards. It looks like [this should be possible](https://www.drupal.org/node/1419980).

**Comment by indytechcook** [comment]
Yes, I use sniffers on all my projects.  I can add my lint files.

**Comment by indytechcook** [comment]
Sorry I haven't been able to put my attention to this.  I have a script to auto reformat the files that I'll run.
