### ISSUE TITLE
Loosening up Guzzle's version requirement

### ISSUE THREAD

**Issue by karllhughes** [betterweekdays/glassdoor#9]
We obviously want to keep Guzzle 6.x, but is there a reason to use ^6.0.2 in the composer file? This forces the package to only work with Guzzle 6.0.x.

It seems that everything works fine if we change it to `~6.0.2`. This allows people to run newer versions of Guzzle but shouldn't break backwards compatibility. Sound okay with you guys?

**Comment by indytechcook** [comment]
No reason, sticking with 6.0.x is good.
